### ISSUE TITLE
CMake config

### ISSUE THREAD

**Issue by unStatiK** [unStatiK/NS#8]
```[tasklist]
## Tasks
- [X] Support Visual studio 2010 - 2022
- [X] Support makefile and GCC
- [X] Support makefile and TCC
- [X] Support x86 Windows
- [X] Support x64 Windows
- [X] Support x86 Linux
- [X] Support x64 Linux
```

**Comment by unStatiK** [comment]
- [ ]
